export const storeInfo = {
  name: "Wegmans",
  location: "Reston, VA",
  manager: "Alex Marshall",
  storeId: "#107",
};

export const atRiskInventory = [
  {
    id: "SKU-001",
    name: "Boneless Chicken Breast",
    category: "Protein",
    quantity: 42,
    unit: "lbs",
    expirationDate: "2026-03-20",
    daysUntilExpiration: 1,
    costPerUnit: 4.99,
    retailPrice: 8.99,
    status: "Critical",
  },
  {
    id: "SKU-002",
    name: "Roma Tomatoes",
    category: "Produce",
    quantity: 28,
    unit: "lbs",
    expirationDate: "2026-03-21",
    daysUntilExpiration: 2,
    costPerUnit: 1.29,
    retailPrice: 2.49,
    status: "Critical",
  },
  {
    id: "SKU-003",
    name: "Baby Spinach",
    category: "Produce",
    quantity: 18,
    unit: "bags",
    expirationDate: "2026-03-21",
    daysUntilExpiration: 2,
    costPerUnit: 2.49,
    retailPrice: 4.99,
    status: "Critical",
  },
  {
    id: "SKU-004",
    name: "Corn Tortillas",
    category: "Bakery",
    quantity: 36,
    unit: "packs",
    expirationDate: "2026-03-22",
    daysUntilExpiration: 3,
    costPerUnit: 1.79,
    retailPrice: 3.49,
    status: "Critical",
  },
  {
    id: "SKU-005",
    name: "Fresh Mozzarella",
    category: "Dairy",
    quantity: 24,
    unit: "balls",
    expirationDate: "2026-03-23",
    daysUntilExpiration: 4,
    costPerUnit: 3.49,
    retailPrice: 6.99,
    status: "At Risk",
  },
  {
    id: "SKU-006",
    name: "Large Eggs",
    category: "Dairy",
    quantity: 60,
    unit: "dozen",
    expirationDate: "2026-03-23",
    daysUntilExpiration: 4,
    costPerUnit: 2.99,
    retailPrice: 5.49,
    status: "At Risk",
  },
  {
    id: "SKU-007",
    name: "Bell Peppers (Mixed)",
    category: "Produce",
    quantity: 32,
    unit: "lbs",
    expirationDate: "2026-03-23",
    daysUntilExpiration: 4,
    costPerUnit: 1.99,
    retailPrice: 3.99,
    status: "At Risk",
  },
  {
    id: "SKU-008",
    name: "Ground Beef 80/20",
    category: "Protein",
    quantity: 35,
    unit: "lbs",
    expirationDate: "2026-03-24",
    daysUntilExpiration: 5,
    costPerUnit: 5.49,
    retailPrice: 9.99,
    status: "At Risk",
  },
  {
    id: "SKU-009",
    name: "Basil (Fresh)",
    category: "Produce",
    quantity: 40,
    unit: "bunches",
    expirationDate: "2026-03-24",
    daysUntilExpiration: 5,
    costPerUnit: 1.49,
    retailPrice: 2.99,
    status: "At Risk",
  },
  {
    id: "SKU-010",
    name: "Russet Potatoes",
    category: "Produce",
    quantity: 50,
    unit: "lbs",
    expirationDate: "2026-03-25",
    daysUntilExpiration: 6,
    costPerUnit: 0.89,
    retailPrice: 1.79,
    status: "Expiring Soon",
  },
  {
    id: "SKU-011",
    name: "Cheddar Cheese Block",
    category: "Dairy",
    quantity: 20,
    unit: "blocks",
    expirationDate: "2026-03-25",
    daysUntilExpiration: 6,
    costPerUnit: 4.29,
    retailPrice: 7.99,
    status: "Expiring Soon",
  },
  {
    id: "SKU-012",
    name: "Sour Cream",
    category: "Dairy",
    quantity: 30,
    unit: "tubs",
    expirationDate: "2026-03-25",
    daysUntilExpiration: 6,
    costPerUnit: 1.99,
    retailPrice: 3.79,
    status: "Expiring Soon",
  },
];

export const bundleRecommendations = [
  {
    id: "BUN-001",
    name: "Chicken Fajita Kit",
    label: "High Demand",
    emoji: "🍗",
    expiryLabel: "Expires in 3 hrs",
    description: "Everything you need for a sizzling weeknight fajita dinner — no shopping list required.",
    ingredients: [
      { skuId: "SKU-001", name: "Chicken Breast", quantity: "1.5 lbs" },
      { skuId: "SKU-007", name: "Bell Peppers", quantity: "0.75 lbs" },
      { skuId: "SKU-004", name: "Corn Tortillas", quantity: "1 pack (12ct)" },
    ],
    serves: 4,
    bundlePrice: 12.99,
    retailValue: 18.97,
    shrinkSavedPerBundle: 9.73,
    bundlesAvailable: 12,
    unitsSold: 8,
    isLive: false,
  },
  {
    id: "BUN-002",
    name: "Caprese Salad Kit",
    label: "Tonight Only",
    emoji: "🥗",
    expiryLabel: "Expires in 5 hrs",
    description: "A restaurant-quality caprese salad in minutes — fresh mozzarella, tomatoes, and basil included.",
    ingredients: [
      { skuId: "SKU-005", name: "Fresh Mozzarella", quantity: "2 balls" },
      { skuId: "SKU-002", name: "Roma Tomatoes", quantity: "1 lb" },
      { skuId: "SKU-009", name: "Fresh Basil", quantity: "1 bunch" },
    ],
    serves: 2,
    bundlePrice: 9.99,
    retailValue: 14.47,
    shrinkSavedPerBundle: 7.23,
    bundlesAvailable: 8,
    unitsSold: 6,
    isLive: false,
  },
  {
    id: "BUN-003",
    name: "Breakfast Scramble Kit",
    label: "Today's Lunch Deal",
    emoji: "🍳",
    expiryLabel: "Expires in 8 hrs",
    description: "A hearty scramble that works for brunch or lunch — eggs, peppers, and cheese all in one grab.",
    ingredients: [
      { skuId: "SKU-006", name: "Large Eggs", quantity: "6 eggs" },
      { skuId: "SKU-007", name: "Bell Peppers", quantity: "0.5 lbs" },
      { skuId: "SKU-011", name: "Cheddar Cheese", quantity: "¼ block" },
    ],
    serves: 2,
    bundlePrice: 7.99,
    retailValue: 11.24,
    shrinkSavedPerBundle: 5.62,
    bundlesAvailable: 15,
    unitsSold: 5,
    isLive: false,
  },
  {
    id: "BUN-004",
    name: "Loaded Baked Potato Kit",
    label: "Tonight Only",
    emoji: "🥔",
    expiryLabel: "Expires in 4 hrs",
    description: "Comfort food made easy — russets, cheddar, sour cream, and all the fixings.",
    ingredients: [
      { skuId: "SKU-010", name: "Russet Potatoes", quantity: "2 lbs" },
      { skuId: "SKU-011", name: "Cheddar Cheese", quantity: "½ block" },
      { skuId: "SKU-012", name: "Sour Cream", quantity: "1 tub" },
    ],
    serves: 4,
    bundlePrice: 10.99,
    retailValue: 15.56,
    shrinkSavedPerBundle: 7.78,
    bundlesAvailable: 10,
    unitsSold: 7,
    isLive: false,
  },
  {
    id: "BUN-005",
    name: "Beef Taco Kit",
    label: "Tonight Only",
    emoji: "🌮",
    expiryLabel: "Expires in 6 hrs",
    description: "Taco Tuesday any day — seasoned beef, corn tortillas, and all your favorite toppings.",
    ingredients: [
      { skuId: "SKU-008", name: "Ground Beef", quantity: "1 lb" },
      { skuId: "SKU-004", name: "Corn Tortillas", quantity: "1 pack (12ct)" },
      { skuId: "SKU-011", name: "Cheddar Cheese", quantity: "¼ block" },
      { skuId: "SKU-012", name: "Sour Cream", quantity: "1 tub" },
    ],
    serves: 4,
    bundlePrice: 13.99,
    retailValue: 20.26,
    shrinkSavedPerBundle: 10.13,
    bundlesAvailable: 9,
    unitsSold: 4,
    isLive: false,
  },
];

export const shrinkTrendData = [
  { date: "Oct 14", shrinkLoss: 1240, kittedRecovery: 310,  bundleRevenue: 124 },
  { date: "Oct 15", shrinkLoss: 1580, kittedRecovery: 790,  bundleRevenue: 248 },
  { date: "Oct 16", shrinkLoss: 980,  kittedRecovery: 490,  bundleRevenue: 168 },
  { date: "Oct 17", shrinkLoss: 2100, kittedRecovery: 1470, bundleRevenue: 389 },
  { date: "Oct 18", shrinkLoss: 1720, kittedRecovery: 1290, bundleRevenue: 312 },
  { date: "Oct 19", shrinkLoss: 1450, kittedRecovery: 1160, bundleRevenue: 298 },
  { date: "Oct 20", shrinkLoss: 2380, kittedRecovery: 0,    bundleRevenue: 0 },
];
